stock_symbols = [
    'BRITANNIA.NS', 'TATACONSUM.NS', 'TITAN.NS', 'NESTLEIND.NS', 'ITC.NS',
    'HEROMOTOCO.NS', 'ULTRACEMCO.NS', 'APOLLOHOSP.NS', 'ADANIENT.NS', 'BAJAJFINSV.NS',
    'BAJFINANCE.NS', 'TATASTEEL.NS', 'ONGC.NS', 'MARUTI.NS', 'HINDALCO.NS',
    'KOTAKBANK.NS', 'NTPC.NS', 'LT.NS', 'TCS.NS', 'RELIANCE.NS',
    'LTIM.NS', 'HDFCLIFE.NS', 'COALINDIA.NS', 'BHARTIARTL.NS', 'BAJAJ-AUTO.NS',
    'INDUSINDBK.NS', 'WIPRO.NS', 'TECHM.NS', 'CIPLA.NS'
    # Add more stock symbols as needed
]
